[package]
name = "rfs-ess"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
once_cell = "1.21.3"
serde = { version = "1", features = ["derive"] }
toml = "0.9.5"
rfs-utils = { path = "../utils" }